### PR TITLE
Check for 'undefined' position array in template.utility.ts

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://github.com/vivo-community/scholars-angular/issues/30

### CODE REVIEW

**Comment by wwelling** [comment]
I would prefer the template to check if property positions is defined rather than a null check in code. This can be done using handlebars condition in https://github.com/vivo-community/scholars-discovery/blob/master/src/main/resources/defaults/directoryViews/people/default.html.

**Comment by wwelling** [comment]
I advocate to prevent calling function with undefined/null arguments over function guards performing null checks on its arguments. It just may be we need better exception handling and reporting.

**Comment by wwelling** [comment]
I could be convinced in this context to have the helper functions avoid failing. However, the template will fail even if a undefined property is attempting to be templated.

**Comment by awoods** [comment]
Closed by solution in scholars-discovery:
https://github.com/vivo-community/scholars-discovery/pull/52

**Pull request closed without merging**
